version: '3.4'

services:
  bulkemail:
    image: bulkemail
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    restart: always
    container_name: bulkemailer
    env_file:
      - .env